name: Site Build and Upload

on: 
  push:
    paths: docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - name: Install gridsome and build
      run: |
       yarn global add @gridsome/cli
       sudo gridsome build
      env:
        CI: true
    
    - name: SSH Server Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: www.websoft9.com 
        port: 22
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        scp_source: dist
        scp_target: /data/wwwroot/devops
        before_script: |
          df -h
        after_script: |
          whoami
